// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HookEventName = "sessionStart" | "sessionResume" | "sessionEnd" | "sessionInterrupted" | "userPromptSubmit" | "turnStart" | "turnComplete" | "turnAbort" | "turnError" | "preToolUse" | "postToolUse" | "toolError" | "permissionRequest" | "permissionDenied" | "approvalGranted" | "taskCreated" | "taskStarted" | "taskCompleted" | "taskFailed" | "subagentStart" | "subagentComplete" | "subagentEscalation" | "fileChanged" | "cwdChanged" | "configChanged" | "memoryUpdated" | "skillChanged" | "compactionStart" | "compactionComplete" | "contextTruncated" | "promptCacheHit" | "promptCacheMiss" | "stop";
